/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CookRouteImport } from './routes/cook'
import { Route as CookTogetherRouteImport } from './routes/cook-together'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CookRoute = CookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => rootRouteImport,
} as any)
const CookTogetherRoute = CookTogetherRouteImport.update({
  id: '/cook-together',
  path: '/cook-together',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/cook': typeof CookRoute
  '/cook-together': typeof CookTogetherRoute
  '/preferences': typeof PreferencesRoute
  '/recipes': typeof RecipesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/cook': typeof CookRoute
  '/cook-together': typeof CookTogetherRoute
  '/preferences': typeof PreferencesRoute
  '/recipes': typeof RecipesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/cook': typeof CookRoute
  '/cook-together': typeof CookTogetherRoute
  '/preferences': typeof PreferencesRoute
  '/recipes': typeof RecipesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/cook'
    | '/cook-together'
    | '/preferences'
    | '/recipes'
    | '/saved'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/cook'
    | '/cook-together'
    | '/preferences'
    | '/recipes'
    | '/saved'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/cook'
    | '/cook-together'
    | '/preferences'
    | '/recipes'
    | '/saved'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  CookRoute: typeof CookRoute
  CookTogetherRoute: typeof CookTogetherRoute
  PreferencesRoute: typeof PreferencesRoute
  RecipesRoute: typeof RecipesRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook': {
      id: '/cook'
      path: '/cook'
      fullPath: '/cook'
      preLoaderRoute: typeof CookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook-together': {
      id: '/cook-together'
      path: '/cook-together'
      fullPath: '/cook-together'
      preLoaderRoute: typeof CookTogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  CookRoute: CookRoute,
  CookTogetherRoute: CookTogetherRoute,
  PreferencesRoute: PreferencesRoute,
  RecipesRoute: RecipesRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
